title: Your Name
description: Web Developer from Somewhere
author: 
baseurl: "/you-might-not-need-jquery-plugins"
markdown: redcarpet
google_analytics:
highlighter: pygments
## Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
